[build]
builder = "DOCKERFILE"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m backend.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 10

[environments.demo]
DEMO_MODE = "true"
USE_SQLITE = "true"
SQLITE_DB_PATH = "/app/demo_pets.db"
ENVIRONMENT = "demo"
LOG_LEVEL = "INFO"